shared:
    image: node:8

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=lib -Dsonar.javascript.lcov.reportPath=artifacts/coverage/lcov.info"
        steps:
            - install: npm install
            - test: npm test
        requires:
            - ~pr
            - ~commit

    publish:
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
        requires:
            - main
