shared:
    image: node:12

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=index.js,lib -Dsonar.tests=test -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/lcov.info -Dsonar.testExecutionReportPaths=artifacts/report/test.xml"
            NODE_OPTIONS: "--max_old_space_size=4096"
        steps:
            - install: npm install
            - test: npm test
        requires:
            - ~pr
            - ~commit

    publish:
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
        requires:
            - main
